name: download afrifacts

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: List artifacts from last successful workflow
        run: |
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github+json" \
              "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" | jq '.artifacts[] | .name'
      - name: Get latest run ID
        id: get-latest-run
        run: |
          LATEST_RUN_ID=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" | jq -r '.artifacts[0].workflow_run.id')
          echo "latest_run_id=$LATEST_RUN_ID" >> $GITHUB_ENV

      - name: Download artifacts from latest successful run
        id: download-artifacts
        uses: actions/download-artifact@v4
        with:
          path: my-artifact
          pattern: my-artifact-*
          merge-multiple: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ env.latest_run_id }}

      - name: Check if artifacts were downloaded
        run: |
          if [ ! -d "my-artifact" ] || [ -z "$(ls -A my-artifact)" ]; then
            echo "No artifacts were downloaded"
            exit 1
          fi
          echo "Artifacts downloaded successfully"

      # - name: Trigger upload workflow
      #   if: success() && steps.download-artifacts.outcome == 'success'
      #   run: |
      #     echo "Triggering upload workflow..."
      #     curl -X POST \
      #       -H "Accept: application/vnd.github+json" \
      #       -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
      #       -H "Content-Type: application/json" \
      #       "https://api.github.com/repos/${{ github.repository }}/actions/workflows/upload.yaml/dispatches" \
      #       -d "{\"ref\":\"${{ github.head_ref }}\"}"
      #     echo "Upload workflow triggered successfully"
