name: upload afrifacts

on:
  workflow_run:
    workflows: ["download afrifacts"]
    types:
      - completed
    branches:
      - ${{ github.head_ref }}

jobs:
  upload:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Create a File
        run: echo "hello from ${{ matrix.runs-on }}" > file-${{ matrix.runs-on }}.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact-2-${{ matrix.runs-on }}
          path: file-${{ matrix.runs-on }}.txt
          retention-days: 1
